name: postchain_client
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  crypto: ^3.0.1
  ecdsa: ^0.0.4
  hex: ^0.2.0
  http: ^0.13.4
  json_serializable: ^5.0.2
  tuple: ^2.0.0
